name: Docker 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-tools:

    runs-on: ubuntu-latest
    container: terraform:1.2.6

    steps:
      - run: docker version
      - run: terraform version
      - run: go version
      - run: id 
