name: Docker 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-tools:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Docker image Build & Push"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAS }}
