name: Docker 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-tools:

    runs-on: ubuntu-latest

    steps:
      - run: echo "Docker image Build & Push"

      - 
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAS }}

      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: glejnhithi/jenkins-git:latest